version: '2.3'

services:

  train:
    build: .

    runtime: nvidia

    volumes:
      - ./:/code

    working_dir: /code


  notebooks:
    build: .

    runtime: nvidia

    ports:
      - "8888:8888"


    volumes:
      - ./:/code

    working_dir: /code

    command: jupyter notebook --no-browser --ip 0.0.0.0 --allow-root --NotebookApp.iopub_data_rate_limit=1.0e10 


  # run:
  #   build: .

  #   runtime: nvidia

  #   ports:
  #     - "4567:4567"

  #   volumes:
  #     - ./:/code
  #     - /tmp/.X11-unix:/tmp/.X11-unix

  #   working_dir: /code

  #   environment:
  #     DISPLAY: $DISPLAY

  #   command: bash pilotnet/scripts/run.sh
