# correction
angle_correction: 0.2

# bins
nbins: 21

# regularization
label_smoothing: 0.2
zeros_weight: 0.1
noise_mean: 0.0
noise_stddev: 0.025

# train
summary_steps: 200
max_steps: 35000
eval_steps: 20
start_delay_secs: 60
throttle_secs: 120

# dataset
batch_size: 64
buffer_size: 1000
n_threads: 4

# image
image_height: 160
image_width: 320
crop_up: 50
crop_down: 25
resize_height: 66
resize_width: 200

# learning rate
cold_learning_rate: 0.000001
learning_rate: 0.01
final_learning_rate: 0.0001

cold_steps: 5000
warmup_steps: 5000
decay_steps: 20000

train_batch_size: 128

