network: pilot

# bins
nbins: 21

# dataset
angle_correction: 0.1
only_center_camera: False
same_direction_camera: 0.0

# regularization
label_smoothing: 0.1
zeros_weight: 0.2
max_weight: 2.0
angle_noise_std: 0.02
l1_embeddings_regularization: 0.00001
l2_regularization: 0.00001
dropout: 0.0

# train
summary_steps: 200
max_steps: 200000
save_checkpoints_steps: 5000
eval_steps: 20
start_delay_secs: 60
throttle_secs: 120

# pipeline
batch_size: 64
buffer_size: 1000
n_threads: 4

# image
image_height: 160
image_width: 320
crop_up: 50
crop_down: 25
resize_height: 66
resize_width: 200

# learning rate
cold_learning_rate:  0.000001
learning_rate: 0.01
final_learning_rate: 0.0001

cold_steps: 0
warmup_steps: 0
decay_steps: 200000
